version: "3.9"

services:
  api_server:
    image: cosmtrek/air:latest
    container_name: api_server
    tty: true
    stdin_open: true
    working_dir: /workspaces
    environment:
      - TZ=Asia/Tokyo
      - DB_USER=app
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_HOST=db
      - DB_DATABASE=app
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/workspaces

  db:
    image: postgres:15.4
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 3
