openapi: 3.1.0
info:
  version: 1.0.0
  title: User Endpoint
servers:
  - url: http://localhost:8080
paths:
  /users/{id}:
    get:
      description: Get user by user id
      operationId: getUserByID
      parameters:
        - name: id
          in: path
          description: ID of user to get
          required: true
          schema:
            x-go-type: uuid.UUID
            x-go-type-import:
              path: github.com/google/uuid
      responses:
        200:
          description: Successfully returned a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
          example: "572db776-4f09-11ee-be56-0242ac120002"
        name:
          type: string
          example: "John Doe"
    Error:
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
