package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/koki-algebra/go_server_sample/internal/infra/graphql/generated/model"
)

// Save is the resolver for the Save field.
func (r *mutationResolver) Save(ctx context.Context, input model.SaveInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Save - Save"))
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.user.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return convertUser(user), nil
}
